### ISSUE TITLE
Server Error for Moxfield decks

### ISSUE THREAD

**Issue by jdstamp** [chilli-axe/mpc-autofill#197]
# System

- **macOS Sonoma 14.0**:
- **Firefox 119.0.1 (64-bit)** and **Safari 17.0**:

# Affected Components

- [x] Backend?
- [ ] Frontend?
- [ ] Desktop Tool

# Description

When I go to either mpcfill.com or mpcautofill.github.io/editor and use a moxfield link (e.g. https://www.moxfield.com/decks/j-0aJlxuOUm9FnKRvJcfZw ) to add cards I get a "Server Error", see screenshot below.

<img width="349" alt="image" src="https://github.com/chilli-axe/mpc-autofill/assets/33094162/441d577b-57e3-4419-93f8-2dfb43dc72f4">

The expected behaviour is that the editor loads the card list.
-

# Steps to Reproduce

Open mpcautofill.github.io/editor and click "add cards > url" and paste any moxfield link.

This problem has been reproduced both on mpcfill.com and mpcautofill.github.io with firefox and safari.

- https://mpcautofill.github.io/editor
- https://www.moxfield.com/decks/j-0aJlxuOUm9FnKRvJcfZw

**Comment by jdstamp** [comment]
Other websites i tried work as expected (e.g. tappedout, mtggoldfish)

**Comment by ndepaola** [comment]
howdy - thanks for reporting this and sorry for the inconvenience! i also noticed it was broken the other day and fixed it in this commit 478e7995a702986ba77d1fcbc20553db75c8d08a (i think it's fine to use request headers like this since we're not scraping their site, but rather we are querying data on a user's behalf)

**Comment by ndepaola** [comment]
looks like this has broken again - imma reach out to the moxfield team and see what we can do

**Comment by ndepaola** [comment]
properly fixed by 9879a5e090ca040be7369c7aaaa390254156bcd1

**Comment by ndepaola** [comment]
> I'm still seeing this issue with Moxfield URLs.
> <img alt="image" width="1676" src="https://private-user-images.githubusercontent.com/16724046/287117561-3874194a-9541-4b2e-bd04-a3a247ee50fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzOTQ3ODMsIm5iZiI6MTcwMTM5NDQ4MywicGF0aCI6Ii8xNjcyNDA0Ni8yODcxMTc1NjEtMzg3NDE5NGEtOTU0MS00YjJlLWJkMDQtYTNhMjQ3ZWU1MGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDAxMzQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MDczNmRhZDVhNGU0ZjU3OTY3NzYwN2NjZDY1MmViZTg5M2NjZTA5ZjdmYjAxMDM1OTFiOTMxN2VhZjk4YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ib4d05A9gqbf0J4mW95tIg047vVRlIBqQSYhRvJj6Lw">
> 
> Payload:
> 
> ```
> {url: "https://www.moxfield.com/decks/hHcoQkbo2kWxXSCNyXGX5A"}
> ```

yep i hear you - to clarify, the software fix is done but the change hasn't been pulled into mpcfill.com yet. you're looking for https://github.com/Investigamer/mpc-fill/pull/9

**Comment by bwsinger** [comment]
Gotcha. I noticed that the `x-reauested-by` header wasn't passed. I'm glad it's all good.

<img width="479" alt="image" src="https://github.com/chilli-axe/mpc-autofill/assets/16724046/d50e3e1d-9f4e-4468-ab6f-f5516db7679c">

**Comment by NagashSzarekh** [comment]
This bug still appears to exist do we have any timeline on when the fix will be pulled into mpcfill.com or mpcautofill.github.io?

**Comment by ndepaola** [comment]
> This bug still appears to exist do we have any timeline on when the fix will be pulled into mpcfill.com or mpcautofill.github.io?

i totally hear your frustration but the correct place to ask this is https://github.com/Investigamer/mpc-fill/pull/9, not here - i have no control over mpcfill.com
